ubuntu@172.31.33.144
[windows]
172.31.35.161
[windows:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_port=5985
ansible_winrm_server_cert_validation=ignore
#ansible_password="{{ ansible_password }}"
ansible_password=F&t!1Uo(q--(kfTpOl@!DRZ.cjx(675c
#ansible_python_interpreter=/home/ubuntu/ansible-venv/bin/python
