---
- name: windows basic authentication
  hosts: windows
  gather_facts: no

  tasks:
    - name: check if pyCharm has been installed before
      win_shell: 'Get-Package | Select-Object -ExpandProperty Name | findstr /i PyCharm'
      register: pycharm_presence
      changed_when: false
      # keep it false to avoid failing when findstr returns 1 (not found)
      failed_when: false
    
    - name: Backup existing PyCharm install directory if present
      ansible.windows.win_shell: |
        if (Test-Path "C:\DataHubCore\PyCharm") { Rename-Item -Path "C:\DataHubCore\PyCharm" -NewName ('PyCharm.old.{0}' -f (Get-Date -Format 'ddMMyyyyHHmmss')) }
      args:
        executable: powershell.exe
      when: pycharm_presence.stdout_lines | default([]) | length == 0

    - name: Install pyCharm
      win_package:
        state: present
        path: 'C:\temp-area\pycharm-2025.3.exe'
        arguments:
          - /S
          - '/D=C:\DataHubCore\Pycharm'
      when: pycharm_presence.stdout_lines | default([]) | length == 0