---
- name: windows basic authentication
  hosts: windows
  gather_facts: no

  tasks:
    - name: check if pyCharm has been installed before
      win_shell: 'Get-Package | Select-Object -ExpandProperty Name | findstr /i PyCharm'
      register: pycharm_presence
      changed_when: false
      # keep it false to avoid failing when findstr returns 1 (not found)
      failed_when: false

    - name: Install pyCharm
      win_package:
        state: present
        path: 'C:\temp-area\pycharm-professional-2021.3.3.exe'
        arguments:
          - /S
          - '/D=C:\DataHubCore\Pycharm'
      when: pycharm_presence.stdout_lines | default([]) | length == 0